name: Build Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: |
          export R2_BUCKET_NAME="exapmple-bucket"
          export R2_DOMAIN="example.com"
          < wrangler.json envsubst > deploy.json
          npx wrangler deploy -c deploy.json --dry-run --outdir=dist

      - name: approve
        if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'takuo/capture'
        run: gh pr review "$PR_URL" --approve --body 'Automated approval for Dependabot updates.'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
